import {
  Book,
  BookOpen,
  Briefcase,
  Building2,
  Camera,
  ChartLine,
  Code,
  Coffee,
  Compass,
  Dumbbell,
  FlaskConical,
  Folder,
  Gamepad2,
  Globe,
  GraduationCap,
  Hammer,
  Heart,
  House,
  Landmark,
  Layers,
  Leaf,
  Lightbulb,
  Music,
  Palette,
  PenTool,
  Plane,
  Rocket,
  ShoppingBag,
  Sparkles,
  Sprout,
  Star,
  Target,
  Users,
  Wallet,
  Wrench,
  Zap,
} from 'lucide-react'

/** Curated icon set: the key is stored in spaces.icon and rendered through this map. */
export const SPACE_ICONS = {
  briefcase: Briefcase,
  leaf: Leaf,
  rocket: Rocket,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  heart: Heart,
  dumbbell: Dumbbell,
  code: Code,
  palette: Palette,
  music: Music,
  plane: Plane,
  house: House,
  camera: Camera,
  coffee: Coffee,
  globe: Globe,
  'flask-conical': FlaskConical,
  sprout: Sprout,
  wallet: Wallet,
  folder: Folder,
  book: Book,
  'building-2': Building2,
  'chart-line': ChartLine,
  compass: Compass,
  'gamepad-2': Gamepad2,
  hammer: Hammer,
  landmark: Landmark,
  lightbulb: Lightbulb,
  'pen-tool': PenTool,
  'shopping-bag': ShoppingBag,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  users: Users,
  wrench: Wrench,
  zap: Zap,
}

export const GLOBAL_ICON = Layers
